### ISSUE TITLE
Cannot find module 'XXXXXX' on Windows

### ISSUE THREAD

**Issue by ctate** [crystal/crystal#2]
Certain modules are not building correctly on Windows, because they require an npm module that wasn't installed during `crystal install` or `crystal update`. As a workaround, users can navigate to the module's directory and run `npm update`.

Working on a fix to be released in v0.8.5.

**Comment by ctate** [comment]
Fixed by v0.8.5: a0c79aef2e379bf58ecbdff11d91aec5b610bf65
